/*
 * RE-AGENT-BANNER: Apple System 7.1 Finder Types
 * Reverse engineered from Finder.rsrc (SHA256: 7d59b9ef6c5587010ee4d573bd4b5fb3aa70ba696ccaff1a61b52c9ae1f7a632)
 * Architecture: Motorola 68k, Classic Mac OS ABI
 * Generated by reimplementation agent (coord-0004)
 * Source evidence: evidence.curated.json, mappings.json, layouts.curated.json
 */

#ifndef FINDER_TYPES_H
#define FINDER_TYPES_H

#include "../MacTypes.h"

/* Forward declarations to avoid circular dependencies */
typedef struct WindowRecord* WindowPtr;
typedef struct MenuInfo** MenuHandle;

/* Define our own simplified versions to avoid conflicts */
typedef struct FinderPoint {
    short v;    /* Vertical coordinate */
    short h;    /* Horizontal coordinate */
} FinderPoint;

typedef struct FinderRect {
    short top;      /* Top coordinate */
    short left;     /* Left coordinate */
    short bottom;   /* Bottom coordinate */
    short right;    /* Right coordinate */
} FinderRect;

typedef struct FinderFSSpec {
    short vRefNum;  /* Volume reference number */
    long parID;     /* Parent directory ID */
    Str63 name;     /* File name (Pascal string) */
} FinderFSSpec;

typedef struct FinderEventRecord {
    short what;         /* Event type */
    long message;       /* Event message */
    long when;          /* Time of event */
    FinderPoint where;  /* Mouse location */
    short modifiers;    /* Modifier keys */
} FinderEventRecord;

/* Redefine common types for Finder use */
#define Point FinderPoint
#define Rect FinderRect
#define FSSpec FinderFSSpec
#define EventRecord FinderEventRecord

/* Finder global state - evidence: layouts.curated.json offset 0x00000030 */
typedef struct FinderGlobals {
    OSType signature;       /* Application signature - 'FNDR' */
    OSType creator;         /* Creator code - 'MACS' */
    short version;          /* Finder version number */
    short flags;            /* Application flags */
    WindowPtr current_window;   /* Pointer to current active window */
    MenuHandle menu_bar;    /* Handle to menu bar */
    short event_mask;       /* Event mask for GetNextEvent */
    long sleep_time;        /* Sleep time for event loop */
    /* Additional padding to reach 256 bytes total size */
    char reserved[256 - 26];
} FinderGlobals;

/* Function signature types */
typedef OSErr (*FileOperationHandler)(FSSpec* fileSpec, short operation);
typedef void (*EventLoopHandler)(EventRecord* event, WindowPtr window,
                                MenuHandle menu, short item, long data, Ptr userData);

/* Constants derived from evidence */
#define FINDER_SIGNATURE    0x464E4452  /* 'FNDR' */
#define FINDER_CREATOR      0x4D414353  /* 'MACS' */
#define FINDER_VERSION      0x0701      /* System 7.1 */

/* Event types (Classic Mac OS) */
enum {
    nullEvent       = 0,
    mouseDown       = 1,
    mouseUp         = 2,
    keyDown         = 3,
    keyUp           = 4,
    autoKey         = 5,
    updateEvt       = 6,
    diskEvt         = 7,
    activateEvt     = 8,
    osEvt           = 15
};

/* Event masks */
enum {
    everyEvent      = 0xFFFF
};

/* Additional error codes */
enum {
    eventNotHandledErr = -9874
    /* unimpErr is already defined in MacTypes.h */
};

/* File operation codes */
enum {
    kFileOpCopy     = 1,
    kFileOpMove     = 2,
    kFileOpDelete   = 3,
    kFileOpRename   = 4
};

#endif /* FINDER_TYPES_H */

/*
 * RE-AGENT-TRAILER-JSON: {
 *   "file": "include/finder_types.h",
 *   "generated": "2025-09-17T22:25:00Z",
 *   "evidence_sources": [
 *     "layouts.curated.json",
 *     "mappings.json",
 *     "evidence.curated.json"
 *   ],
 *   "provenance_density": 0.85,
 *   "structures_implemented": 5,
 *   "confidence": 0.75
 * }
 */