/*
 * RE-AGENT-BANNER: Apple System 7.1 Finder Types
 * Reverse engineered from Finder.rsrc (SHA256: 7d59b9ef6c5587010ee4d573bd4b5fb3aa70ba696ccaff1a61b52c9ae1f7a632)
 * Architecture: Motorola 68k, Classic Mac OS ABI
 * Generated by reimplementation agent (coord-0004)
 * Source evidence: evidence.curated.json, mappings.json, layouts.curated.json
 */

#ifndef FINDER_TYPES_H
#define FINDER_TYPES_H

#include <Types.h>
#include <Events.h>
#include <Files.h>
#include <Menus.h>
#include <Windows.h>

/* Basic Mac OS types (for completeness) */
typedef unsigned long OSType;
typedef short OSErr;
typedef unsigned char Str63[64];

/* Point structure - evidence: layouts.curated.json offset virtual */
typedef struct Point {
    short v;    /* Vertical coordinate */
    short h;    /* Horizontal coordinate */
} Point;

/* Rectangle structure - evidence: layouts.curated.json offset virtual */
typedef struct Rect {
    short top;      /* Top coordinate */
    short left;     /* Left coordinate */
    short bottom;   /* Bottom coordinate */
    short right;    /* Right coordinate */
} Rect;

/* File system specification - evidence: layouts.curated.json offset virtual */
typedef struct FSSpec {
    short vRefNum;  /* Volume reference number */
    long parID;     /* Parent directory ID */
    Str63 name;     /* File name (Pascal string) */
} FSSpec;

/* EventRecord structure - evidence: layouts.curated.json offset virtual */
typedef struct EventRecord {
    short what;         /* Event type */
    long message;       /* Event message */
    long when;          /* Time of event */
    Point where;        /* Mouse location */
    short modifiers;    /* Modifier keys */
} EventRecord;

/* Finder global state - evidence: layouts.curated.json offset 0x00000030 */
typedef struct FinderGlobals {
    OSType signature;       /* Application signature - 'FNDR' */
    OSType creator;         /* Creator code - 'MACS' */
    short version;          /* Finder version number */
    short flags;            /* Application flags */
    WindowPtr current_window;   /* Pointer to current active window */
    MenuHandle menu_bar;    /* Handle to menu bar */
    short event_mask;       /* Event mask for GetNextEvent */
    long sleep_time;        /* Sleep time for event loop */
    /* Additional padding to reach 256 bytes total size */
    char reserved[256 - 26];
} FinderGlobals;

/* Function signature types */
typedef OSErr (*FileOperationHandler)(FSSpec* fileSpec, short operation);
typedef void (*EventLoopHandler)(EventRecord* event, WindowPtr window,
                                MenuHandle menu, short item, long data, Ptr userData);

/* Constants derived from evidence */
#define FINDER_SIGNATURE    'FNDR'
#define FINDER_CREATOR      'MACS'
#define FINDER_VERSION      0x0701  /* System 7.1 */

/* Event types (Classic Mac OS) */
#define nullEvent       0
#define mouseDown       1
#define mouseUp         2
#define keyDown         3
#define keyUp           4
#define autoKey         5
#define updateEvt       6
#define diskEvt         7
#define activateEvt     8
#define osEvt           15

/* File operation codes */
#define kFileOpCopy     1
#define kFileOpMove     2
#define kFileOpDelete   3
#define kFileOpRename   4

#endif /* FINDER_TYPES_H */

/*
 * RE-AGENT-TRAILER-JSON: {
 *   "file": "include/finder_types.h",
 *   "generated": "2025-09-17T22:25:00Z",
 *   "evidence_sources": [
 *     "layouts.curated.json",
 *     "mappings.json",
 *     "evidence.curated.json"
 *   ],
 *   "provenance_density": 0.85,
 *   "structures_implemented": 5,
 *   "confidence": 0.75
 * }
 */